import React from 'react';
import {
  View,
  Text,
  TouchableOpacity,
  StyleSheet,
  ScrollView,
} from 'react-native';

const movies = [
  {
    id: '1',
    title: 'Harry Potter and the Sorcerer’s Stone',
    year: '2001',
    genre: 'Fantasy',
    rating: '7.6',
    color: '#263238',
    description: 'A young wizard begins his magical education at Hogwarts.',
  },
  {
    id: '2',
    title: 'Harry Potter and the Chamber of Secrets',
    year: '2002',
    genre: 'Fantasy',
    rating: '7.4',
    color: '#37474F',
    description: 'Harry returns to Hogwarts and discovers a mysterious hidden chamber.',
  },
  {
    id: '3',
    title: 'Harry Potter and the Prisoner of Azkaban',
    year: '2004',
    genre: 'Fantasy',
    rating: '7.9',
    color: '#455A64',
    description: 'Harry learns more about his past while a dangerous prisoner escapes.',
  },
  {
    id: '4',
    title: 'The Lord of the Rings',
    year: '2001',
    genre: 'Fantasy',
    rating: '8.9',
    color: '#3E2723',
    description: 'A young hobbit begins a dangerous journey to destroy a powerful ring.',
  },
  {
    id: '5',
    title: 'The Hobbit',
    year: '2012',
    genre: 'Fantasy',
    rating: '7.8',
    color: '#4E342E',
    description: 'Bilbo Baggins joins a group of dwarves on an unexpected adventure.',
  },
  {
    id: '6',
    title: 'The Chronicles of Narnia',
    year: '2005',
    genre: 'Fantasy',
    rating: '6.9',
    color: '#1B5E20',
    description: 'Four siblings discover a magical world hidden inside a wardrobe.',
  },
  {
    id: '7',
    title: 'Maleficent',
    year: '2014',
    genre: 'Fantasy',
    rating: '6.9',
    color: '#4A148C',
    description: 'A powerful fairy becomes connected to the fate of a young princess.',
  },
  {
    id: '8',
    title: 'Alice in Wonderland',
    year: '2010',
    genre: 'Fantasy',
    rating: '6.4',
    color: '#283593',
    description: 'Alice returns to a strange world filled with unusual characters.',
  },
  {
    id: '9',
    title: 'The Golden Compass',
    year: '2007',
    genre: 'Fantasy',
    rating: '6.1',
    color: '#1565C0',
    description: 'A young girl travels across a mysterious parallel world.',
  },
  {
    id: '10',
    title: 'Stardust',
    year: '2007',
    genre: 'Fantasy',
    rating: '7.6',
    color: '#512DA8',
    description: 'A young man enters a magical kingdom to find a fallen star.',
  },

  {
    id: '11',
    title: 'Carol',
    year: '2015',
    genre: 'GL / Romance',
    rating: '7.7',
    color: '#880E4F',
    description: 'Two women form a meaningful relationship despite social expectations.',
  },
  {
    id: '12',
    title: 'Portrait of a Lady on Fire',
    year: '2019',
    genre: 'GL / Romance',
    rating: '8.1',
    color: '#6D4C41',
    description: 'An artist develops a close connection with the woman she is painting.',
  },
  {
    id: '13',
    title: 'The Handmaiden',
    year: '2016',
    genre: 'GL / Thriller',
    rating: '8.1',
    color: '#4A235A',
    description: 'Two women become connected through a complicated plan and unexpected feelings.',
  },
  {
    id: '14',
    title: 'Saving Face',
    year: '2004',
    genre: 'GL / Romance',
    rating: '7.4',
    color: '#AD1457',
    description: 'A young doctor balances family expectations and her romantic life.',
  },
  {
    id: '15',
    title: 'Imagine Me & You',
    year: '2005',
    genre: 'GL / Romance',
    rating: '6.7',
    color: '#C2185B',
    description: 'A wedding creates an unexpected connection between two women.',
  },
  {
    id: '16',
    title: 'The World to Come',
    year: '2020',
    genre: 'GL / Drama',
    rating: '6.4',
    color: '#5D4037',
    description: 'Two women living in the 19th century form a deep emotional bond.',
  },
  {
    id: '17',
    title: 'Disobedience',
    year: '2017',
    genre: 'GL / Drama',
    rating: '6.6',
    color: '#37474F',
    description: 'Two women reconnect after years apart and face difficult choices.',
  },
  {
    id: '18',
    title: 'Ammonite',
    year: '2020',
    genre: 'GL / Drama',
    rating: '6.5',
    color: '#455A64',
    description: 'Two women develop a relationship while living on the English coast.',
  },
  {
    id: '19',
    title: 'The Half of It',
    year: '2020',
    genre: 'GL / Romance',
    rating: '6.9',
    color: '#00838F',
    description: 'A student secretly helps a classmate write love letters.',
  },
  {
    id: '20',
    title: 'Crush',
    year: '2022',
    genre: 'GL / Comedy',
    rating: '6.3',
    color: '#AD1457',
    description: 'A young artist joins her school track team and discovers unexpected feelings.',
  },

  {
    id: '21',
    title: 'Frozen',
    year: '2013',
    genre: 'Disney / Animation',
    rating: '7.4',
    color: '#0277BD',
    description: 'A princess searches for her sister after a magical winter covers their kingdom.',
  },
  {
    id: '22',
    title: 'Frozen II',
    year: '2019',
    genre: 'Disney / Animation',
    rating: '6.8',
    color: '#006064',
    description: 'Elsa and her friends travel beyond their kingdom to discover its past.',
  },
  {
    id: '23',
    title: 'Tangled',
    year: '2010',
    genre: 'Disney / Animation',
    rating: '7.7',
    color: '#6A1B9A',
    description: 'A princess with magical hair leaves her tower for the first time.',
  },
  {
    id: '24',
    title: 'Moana',
    year: '2016',
    genre: 'Disney / Adventure',
    rating: '7.6',
    color: '#00838F',
    description: 'A young girl sails across the ocean to save her island.',
  },
  {
    id: '25',
    title: 'Encanto',
    year: '2021',
    genre: 'Disney / Animation',
    rating: '7.2',
    color: '#6A1B9A',
    description: 'A young woman discovers her place in a magical family.',
  },
  {
    id: '26',
    title: 'The Lion King',
    year: '1994',
    genre: 'Disney / Animation',
    rating: '8.5',
    color: '#E65100',
    description: 'A young lion must find his courage and take his place as king.',
  },
  {
    id: '27',
    title: 'Mulan',
    year: '1998',
    genre: 'Disney / Adventure',
    rating: '7.7',
    color: '#B71C1C',
    description: 'A young woman disguises herself as a soldier to protect her family.',
  },
  {
    id: '28',
    title: 'Coco',
    year: '2017',
    genre: 'Animation / Family',
    rating: '8.4',
    color: '#4A148C',
    description: 'A young musician enters the Land of the Dead and discovers his family history.',
  },
  {
    id: '29',
    title: 'Zootopia',
    year: '2016',
    genre: 'Animation / Comedy',
    rating: '8.0',
    color: '#2E7D32',
    description: 'A determined rabbit police officer investigates a mysterious case.',
  },
  {
    id: '30',
    title: 'Ratatouille',
    year: '2007',
    genre: 'Animation / Comedy',
    rating: '8.1',
    color: '#C62828',
    description: 'A talented rat dreams of becoming a chef in Paris.',
  },

  {
    id: '31',
    title: 'Iron Man',
    year: '2008',
    genre: 'Hero / Action',
    rating: '7.9',
    color: '#B71C1C',
    description: 'A billionaire inventor creates a powerful armored suit.',
  },
  {
    id: '32',
    title: 'Captain America: The First Avenger',
    year: '2011',
    genre: 'Hero / Action',
    rating: '6.9',
    color: '#0D47A1',
    description: 'A determined soldier becomes a symbol of hope during wartime.',
  },
  {
    id: '33',
    title: 'Thor',
    year: '2011',
    genre: 'Hero / Fantasy',
    rating: '7.0',
    color: '#37474F',
    description: 'A powerful warrior is sent to Earth and learns responsibility.',
  },
  {
    id: '34',
    title: 'The Avengers',
    year: '2012',
    genre: 'Hero / Action',
    rating: '8.0',
    color: '#263238',
    description: 'A team of heroes joins forces to protect Earth from a major threat.',
  },
  {
    id: '35',
    title: 'Black Panther',
    year: '2018',
    genre: 'Hero / Action',
    rating: '7.3',
    color: '#311B92',
    description: 'A new king must protect his nation and face a powerful challenger.',
  },
  {
    id: '36',
    title: 'Wonder Woman',
    year: '2017',
    genre: 'Hero / Action',
    rating: '7.3',
    color: '#880E4F',
    description: 'A warrior leaves her island to help stop a devastating war.',
  },
  {
    id: '37',
    title: 'Man of Steel',
    year: '2013',
    genre: 'Hero / Action',
    rating: '7.1',
    color: '#1565C0',
    description: 'A powerful alien discovers his identity and chooses to protect Earth.',
  },
  {
    id: '38',
    title: 'Shazam!',
    year: '2019',
    genre: 'Hero / Comedy',
    rating: '7.0',
    color: '#F57F17',
    description: 'A teenager receives magical powers and learns how to become a hero.',
  },
  {
    id: '39',
    title: 'Aquaman',
    year: '2018',
    genre: 'Hero / Adventure',
    rating: '6.8',
    color: '#006064',
    description: 'A powerful hero must claim his place as ruler of an underwater kingdom.',
  },
  {
    id: '40',
    title: 'Spider-Man: Homecoming',
    year: '2017',
    genre: 'Hero / Action',
    rating: '7.4',
    color: '#B71C1C',
    description: 'A young superhero tries to balance school life with protecting his city.',
  },

  {
    id: '41',
    title: 'Train to Busan',
    year: '2016',
    genre: 'Zombie / Thriller',
    rating: '7.6',
    color: '#263238',
    description: 'Passengers fight to survive when a zombie outbreak spreads across a train.',
  },
  {
    id: '42',
    title: 'World War Z',
    year: '2013',
    genre: 'Zombie / Action',
    rating: '7.0',
    color: '#37474F',
    description: 'A former investigator searches for a way to stop a global zombie outbreak.',
  },
  {
    id: '43',
    title: 'Zombieland',
    year: '2009',
    genre: 'Zombie / Comedy',
    rating: '7.5',
    color: '#33691E',
    description: 'A group of survivors travels across a zombie-filled America.',
  },
  {
    id: '44',
    title: 'Warm Bodies',
    year: '2013',
    genre: 'Zombie / Romance',
    rating: '6.8',
    color: '#6D4C41',
    description: 'An unusual friendship begins between a zombie and a human survivor.',
  },
  {
    id: '45',
    title: 'Army of the Dead',
    year: '2021',
    genre: 'Zombie / Action',
    rating: '5.7',
    color: '#424242',
    description: 'A group enters a zombie-infested city for a dangerous mission.',
  },
  {
    id: '46',
    title: '28 Days Later',
    year: '2002',
    genre: 'Zombie / Horror',
    rating: '7.5',
    color: '#1B5E20',
    description: 'A man wakes up to discover that society has been devastated by an infection.',
  },
  {
    id: '47',
    title: 'Resident Evil',
    year: '2002',
    genre: 'Zombie / Action',
    rating: '6.6',
    color: '#212121',
    description: 'A team enters an underground facility after a dangerous virus spreads.',
  },
  {
    id: '48',
    title: 'Dawn of the Dead',
    year: '2004',
    genre: 'Zombie / Horror',
    rating: '7.3',
    color: '#33691E',
    description: 'Survivors take shelter inside a shopping mall during a zombie outbreak.',
  },
  {
    id: '49',
    title: 'Army of Thieves',
    year: '2021',
    genre: 'Zombie / Heist',
    rating: '6.4',
    color: '#4E342E',
    description: 'A group of criminals plans vault robberies during a zombie outbreak.',
  },
  {
    id: '50',
    title: 'Little Monsters',
    year: '2019',
    genre: 'Zombie / Comedy',
    rating: '6.3',
    color: '#827717',
    description: 'A teacher and children try to survive a sudden zombie attack.',
  },
  {
    id: '51',
    title: 'Parasite',
    year: '2019',
    genre: 'Korean / Thriller',
    rating: '8.5',
    color: '#263238',
    description: 'A struggling family becomes involved with a wealthy household.',
  },
  {
    id: '52',
    title: 'The Host',
    year: '2006',
    genre: 'Korean / Monster',
    rating: '7.1',
    color: '#00695C',
    description: 'A family searches for a loved one taken by a mysterious creature.',
  },
  {
    id: '53',
    title: 'Oldboy',
    year: '2003',
    genre: 'Korean / Thriller',
    rating: '8.3',
    color: '#212121',
    description: 'A man investigates the mystery behind his long imprisonment.',
  },
  {
    id: '54',
    title: 'Decision to Leave',
    year: '2022',
    genre: 'Korean / Mystery',
    rating: '7.3',
    color: '#37474F',
    description: 'A detective becomes emotionally involved while investigating a suspicious death.',
  },
  {
    id: '55',
    title: 'Burning',
    year: '2018',
    genre: 'Korean / Mystery',
    rating: '7.5',
    color: '#5D4037',
    description: 'A young man becomes suspicious after meeting an old friend and her mysterious companion.',
  },
  {
    id: '56',
    title: 'The Wailing',
    year: '2016',
    genre: 'Korean / Horror',
    rating: '7.4',
    color: '#33691E',
    description: 'A police officer investigates strange events occurring in a rural village.',
  },
  {
    id: '57',
    title: 'A Taxi Driver',
    year: '2017',
    genre: 'Korean / Drama',
    rating: '7.9',
    color: '#E65100',
    description: 'A taxi driver becomes involved in an important historical event.',
  },
  {
    id: '58',
    title: 'Extreme Job',
    year: '2019',
    genre: 'Korean / Comedy',
    rating: '7.0',
    color: '#BF360C',
    description: 'Detectives run a fried chicken restaurant while secretly investigating criminals.',
  },
  {
    id: '59',
    title: 'Along with the Gods',
    year: '2017',
    genre: 'Korean / Fantasy',
    rating: '7.2',
    color: '#4A148C',
    description: 'A firefighter travels through the afterlife and faces a series of trials.',
  },
  {
    id: '60',
    title: 'The Beauty Inside',
    year: '2015',
    genre: 'Korean / Romance',
    rating: '7.3',
    color: '#6A1B9A',
    description: 'A person wakes up in a different body every day while searching for love.',
  },

  {
    id: '61',
    title: 'The School for Good and Evil',
    year: '2022',
    genre: 'Fantasy',
    rating: '5.9',
    color: '#512DA8',
    description: 'Two friends are taken to a magical school where heroes and villains are trained.',
  },
  {
    id: '62',
    title: 'Enola Holmes',
    year: '2020',
    genre: 'Mystery / Adventure',
    rating: '6.6',
    color: '#37474F',
    description: 'A young detective searches for her missing mother.',
  },
  {
    id: '63',
    title: 'The Princess Bride',
    year: '1987',
    genre: 'Fantasy / Romance',
    rating: '8.0',
    color: '#6A1B9A',
    description: 'A young woman and her true love become part of an unforgettable adventure.',
  },
  {
    id: '64',
    title: 'Beauty and the Beast',
    year: '1991',
    genre: 'Disney / Fantasy',
    rating: '8.0',
    color: '#827717',
    description: 'A young woman discovers kindness and love inside an enchanted castle.',
  },
  {
    id: '65',
    title: 'Aladdin',
    year: '1992',
    genre: 'Disney / Fantasy',
    rating: '8.0',
    color: '#1565C0',
    description: 'A young man discovers a magical lamp and a powerful genie.',
  },
  {
    id: '66',
    title: 'Blue Is the Warmest Color',
    year: '2013',
    genre: 'GL / Drama',
    rating: '7.7',
    color: '#1565C0',
    description: 'A young woman discovers love and identity through an important relationship.',
  },
  {
    id: '67',
    title: 'The Miseducation of Cameron Post',
    year: '2018',
    genre: 'GL / Drama',
    rating: '6.9',
    color: '#37474F',
    description: 'A teenager finds friendship and strength while facing a difficult environment.',
  },
  {
    id: '68',
    title: 'My First Summer',
    year: '2020',
    genre: 'GL / Drama',
    rating: '6.8',
    color: '#2E7D32',
    description: 'Two teenage girls develop a close friendship during a summer away from others.',
  },
  {
    id: '69',
    title: 'Summerland',
    year: '2020',
    genre: 'GL / Drama',
    rating: '7.0',
    color: '#5D4037',
    description: 'A writer develops an unexpected connection while caring for a young boy.',
  },
  {
    id: '70',
    title: 'Ellie & Abbie',
    year: '2020',
    genre: 'GL / Comedy',
    rating: '6.5',
    color: '#AD1457',
    description: 'A teenager prepares for a school dance while navigating her first relationship.',
  },

  {
    id: '71',
    title: 'Toy Story',
    year: '1995',
    genre: 'Animation / Family',
    rating: '8.3',
    color: '#1565C0',
    description: 'Toys come to life when their owner leaves the room.',
  },
  {
    id: '72',
    title: 'Toy Story 3',
    year: '2010',
    genre: 'Animation / Family',
    rating: '8.3',
    color: '#2E7D32',
    description: 'Andy prepares to leave for college while his toys face a new future.',
  },
  {
    id: '73',
    title: 'Inside Out',
    year: '2015',
    genre: 'Animation / Family',
    rating: '8.1',
    color: '#6A1B9A',
    description: 'The emotions inside a young girl’s mind try to help her adjust to a new life.',
  },
  {
    id: '74',
    title: 'Up',
    year: '2009',
    genre: 'Animation / Adventure',
    rating: '8.3',
    color: '#0277BD',
    description: 'An elderly man travels to South America using a house lifted by balloons.',
  },
  {
    id: '75',
    title: 'Big Hero 6',
    year: '2014',
    genre: 'Disney / Animation',
    rating: '7.8',
    color: '#C62828',
    description: 'A young inventor and his friends become a team of heroes.',
  },
  {
    id: '76',
    title: 'Doctor Strange',
    year: '2016',
    genre: 'Hero / Fantasy',
    rating: '7.5',
    color: '#4A148C',
    description: 'A surgeon discovers the world of magic after a life-changing accident.',
  },
  {
    id: '77',
    title: 'Guardians of the Galaxy',
    year: '2014',
    genre: 'Hero / Adventure',
    rating: '8.0',
    color: '#283593',
    description: 'A group of unlikely heroes joins together to protect the galaxy.',
  },
  {
    id: '78',
    title: 'Ant-Man',
    year: '2015',
    genre: 'Hero / Comedy',
    rating: '7.0',
    color: '#455A64',
    description: 'A thief becomes a superhero with the ability to shrink in size.',
  },
  {
    id: '79',
    title: 'Captain Marvel',
    year: '2019',
    genre: 'Hero / Action',
    rating: '6.8',
    color: '#B71C1C',
    description: 'A powerful hero discovers her identity and her connection to Earth.',
  },
  {
    id: '80',
    title: 'Black Widow',
    year: '2021',
    genre: 'Hero / Action',
    rating: '6.6',
    color: '#212121',
    description: 'Natasha confronts her past and reunites with people from her earlier life.',
  },

  {
    id: '81',
    title: 'Shaun of the Dead',
    year: '2004',
    genre: 'Zombie / Comedy',
    rating: '7.9',
    color: '#B71C1C',
    description: 'An ordinary man tries to survive a zombie apocalypse with his friends.',
  },
  {
    id: '82',
    title: 'Peninsula',
    year: '2020',
    genre: 'Zombie / Action',
    rating: '5.5',
    color: '#37474F',
    description: 'A former soldier returns to a zombie-filled Korea for a dangerous mission.',
  },
  {
    id: '83',
    title: 'Alive',
    year: '2020',
    genre: 'Korean / Zombie',
    rating: '6.3',
    color: '#263238',
    description: 'A young man becomes trapped inside his apartment during a sudden outbreak.',
  },
  {
    id: '84',
    title: 'The Girl with All the Gifts',
    year: '2016',
    genre: 'Zombie / Drama',
    rating: '6.6',
    color: '#1B5E20',
    description: 'A special child may hold the key to humanity’s future after an infection spreads.',
  },
  {
    id: '85',
    title: 'Resident Evil: Apocalypse',
    year: '2004',
    genre: 'Zombie / Action',
    rating: '6.1',
    color: '#212121',
    description: 'Survivors fight their way through a city overwhelmed by infected creatures.',
  },
  {
    id: '86',
    title: 'Along with the Gods: The Last 49 Days',
    year: '2018',
    genre: 'Korean / Fantasy',
    rating: '7.1',
    color: '#512DA8',
    description: 'Three guardians continue their journey through the afterlife.',
  },
  {
    id: '87',
    title: 'Be With You',
    year: '2018',
    genre: 'Korean / Romance',
    rating: '7.7',
    color: '#0277BD',
    description: 'A man is reunited with his wife under mysterious circumstances.',
  },
  {
    id: '88',
    title: 'Midnight Runners',
    year: '2017',
    genre: 'Korean / Action',
    rating: '7.3',
    color: '#1565C0',
    description: 'Two police academy students investigate a kidnapping on their own.',
  },
  {
    id: '89',
    title: 'The Outlaws',
    year: '2017',
    genre: 'Korean / Action',
    rating: '7.2',
    color: '#424242',
    description: 'A detective and his team work to control a violent criminal group.',
  },
  {
    id: '90',
    title: 'The Villainess',
    year: '2017',
    genre: 'Korean / Action',
    rating: '6.6',
    color: '#4A148C',
    description: 'A highly trained assassin tries to build a new life while facing her past.',
  },

  {
    id: '91',
    title: 'Jumanji: Welcome to the Jungle',
    year: '2017',
    genre: 'Fantasy / Adventure',
    rating: '6.9',
    color: '#2E7D32',
    description: 'Four students become trapped inside a dangerous video game world.',
  },
  {
    id: '92',
    title: 'The Maze Runner',
    year: '2014',
    genre: 'Adventure / Sci-Fi',
    rating: '6.8',
    color: '#455A64',
    description: 'A group of teenagers must escape a mysterious maze.',
  },
  {
    id: '93',
    title: 'Divergent',
    year: '2014',
    genre: 'Action / Sci-Fi',
    rating: '6.6',
    color: '#5D4037',
    description: 'A young woman discovers that she does not fit into society’s strict system.',
  },
  {
    id: '94',
    title: 'The Hunger Games: Catching Fire',
    year: '2013',
    genre: 'Action / Drama',
    rating: '7.5',
    color: '#B71C1C',
    description: 'Katniss returns to the arena while unrest grows across the districts.',
  },
  {
    id: '95',
    title: 'Avatar',
    year: '2009',
    genre: 'Fantasy / Adventure',
    rating: '7.8',
    color: '#0277BD',
    description: 'A former soldier becomes involved in the struggle of an alien world.',
  },
  {
    id: '96',
    title: 'The Greatest Showman',
    year: '2017',
    genre: 'Musical / Drama',
    rating: '7.5',
    color: '#880E4F',
    description: 'A performer creates a spectacular show and brings together outsiders.',
  },
  {
    id: '97',
    title: 'Your Name',
    year: '2016',
    genre: 'Anime / Romance',
    rating: '8.4',
    color: '#283593',
    description: 'Two teenagers mysteriously begin experiencing each other’s lives.',
  },
  {
    id: '98',
    title: 'Weathering with You',
    year: '2019',
    genre: 'Anime / Fantasy',
    rating: '7.4',
    color: '#0277BD',
    description: 'A teenager meets a girl who seems to control the weather.',
  },
  {
    id: '99',
    title: 'Spirited Away',
    year: '2001',
    genre: 'Anime / Fantasy',
    rating: '8.6',
    color: '#00695C',
    description: 'A young girl enters a mysterious spirit world and searches for a way home.',
  },
  {
    id: '100',
    title: 'Howl’s Moving Castle',
    year: '2004',
    genre: 'Anime / Fantasy',
    rating: '8.2',
    color: '#6A1B9A',
    description: 'A young woman becomes involved with a mysterious wizard and his magical castle.',
  },
];

export default function MovieListScreen({ navigation }) {
  return (
    <ScrollView
      style={styles.container}
      contentContainerStyle={styles.content}
    >
      <Text style={styles.heading}>
        MOVIE COLLECTION
      </Text>

      <Text style={styles.subtitle}>
        100 movies to explore.
      </Text>

      <View style={styles.categoryBox}>
        <Text style={styles.categoryText}>
          FANTASY • GL • CARTOONS • HEROES • ZOMBIES • KOREAN
        </Text>
      </View>

      {movies.map((movie) => (
        <TouchableOpacity
          key={movie.id}
          style={styles.card}
          onPress={() =>
            navigation.navigate('MovieDetails', {
              movie: movie,
            })
          }
        >
          <View
            style={[
              styles.poster,
              { backgroundColor: movie.color },
            ]}
          >
            <Text style={styles.posterText}>
              {movie.title.substring(0, 2).toUpperCase()}
            </Text>
          </View>

          <View style={styles.info}>
            <Text style={styles.title}>
              {movie.title}
            </Text>

            <Text style={styles.genre}>
              {movie.genre}
            </Text>

            <Text style={styles.year}>
              {movie.year} • ★ {movie.rating}
            </Text>

            <Text style={styles.details}>
              VIEW DETAILS →
            </Text>
          </View>
        </TouchableOpacity>
      ))}

      <TouchableOpacity
        style={styles.homeButton}
        onPress={() => navigation.navigate('Home')}
      >
        <Text style={styles.homeButtonText}>
          ← BACK TO HOME
        </Text>
      </TouchableOpacity>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0D0D0D',
  },

  content: {
    padding: 18,
    paddingBottom: 35,
  },

  heading: {
    color: '#FFFFFF',
    fontSize: 22,
    fontWeight: 'bold',
    marginTop: 8,
  },

  subtitle: {
    color: '#888888',
    fontSize: 13,
    marginTop: 7,
    marginBottom: 15,
  },

  categoryBox: {
    backgroundColor: '#163522',
    padding: 12,
    borderRadius: 7,
    marginBottom: 18,
  },

  categoryText: {
    color: '#9CC7A0',
    fontSize: 10,
    fontWeight: 'bold',
    textAlign: 'center',
    letterSpacing: 0.5,
  },

  card: {
    flexDirection: 'row',
    backgroundColor: '#171717',
    borderRadius: 10,
    padding: 10,
    marginBottom: 13,
    borderWidth: 1,
    borderColor: '#292929',
  },

  poster: {
    width: 82,
    height: 116,
    borderRadius: 7,
    justifyContent: 'center',
    alignItems: 'center',
  },

  posterText: {
    color: '#FFFFFF',
    fontSize: 23,
    fontWeight: 'bold',
  },

  info: {
    flex: 1,
    paddingLeft: 14,
    justifyContent: 'center',
  },

  title: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 6,
  },

  genre: {
    color: '#AAAAAA',
    fontSize: 12,
    marginBottom: 7,
  },

  year: {
    color: '#69966C',
    fontSize: 12,
    marginBottom: 12,
  },

  details: {
    color: '#DC143C',
    fontSize: 11,
    fontWeight: 'bold',
  },

  homeButton: {
    backgroundColor: '#DC143C',
    paddingVertical: 15,
    borderRadius: 8,
    alignItems: 'center',
    marginTop: 10,
  },

  homeButtonText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: 'bold',
    letterSpacing: 1,
  },
});